# Generated by Django 5.0.6 on 2024-07-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
    ]
