# Generated by Django 5.0.6 on 2024-07-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('idlocal', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField()),
                ('nombre', models.CharField()),
            ],
            options={
                'db_table': 'local',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localproducto',
            fields=[
                ('idlocalprod', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'localproducto',
                'managed': False,
            },
        ),
    ]
