# Generated by Django 5.0.6 on 2024-07-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='localproducto',
            table='local',
        ),
    ]
