# Generated by Django 5.0.6 on 2024-07-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locales', '0002_alter_localproducto_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='localproducto',
            table='localproducto',
        ),
    ]
