# Generated by Django 5.0.6 on 2024-07-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('idruta', models.AutoField(primary_key=True, serialize=False)),
                ('transporte', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ruta',
                'managed': False,
            },
        ),
    ]
