# Generated by Django 5.0.6 on 2024-07-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('idubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, null=True)),
                ('distrito', models.CharField(blank=True, null=True)),
                ('region', models.CharField(blank=True, null=True)),
                ('lonigtud', models.IntegerField(blank=True, null=True)),
                ('latitud', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ubicacion',
                'managed': False,
            },
        ),
    ]
