# Generated by Django 5.0.6 on 2024-07-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresario',
            fields=[
                ('idempresario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField()),
                ('apellidos', models.CharField()),
                ('correo', models.CharField()),
                ('ruc', models.IntegerField()),
            ],
            options={
                'db_table': 'empresario',
                'managed': False,
            },
        ),
    ]
